# Generated by Django 6.0.7 on 2026-08-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0002_videocategory_alter_video_options_video_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='action',
            field=models.CharField(choices=[('approved', '通过'), ('rejected', '拒绝'), ('published', '已发布')], max_length=20, verbose_name='操作'),
        ),
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专辑名称')),
                ('description', models.TextField(blank=True, verbose_name='专辑简介')),
                ('cover_image', models.ImageField(blank=True, upload_to='album_covers/', verbose_name='专辑封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='users.teacherprofile', verbose_name='教师')),
                ('videos', models.ManyToManyField(blank=True, related_name='albums', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频专辑',
                'verbose_name_plural': '视频专辑',
                'ordering': ['-created_at'],
            },
        ),
    ]
