# Generated by Django 6.0.7 on 2026-08-02 06:47

from django.db import migrations, models
def create_default_setting(apps, schema_editor):
    VideoSetting = apps.get_model('videos', 'VideoSetting')
    VideoSetting.objects.get_or_create(pk=1)




class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_reviewlog_action_videoalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='设置ID')),
                ('default_cover', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='全局默认视频封面')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频设置',
                'verbose_name_plural': '视频设置',
            },
        ),
        migrations.RunPython(create_default_setting, migrations.RunPython.noop),
    ]
