# Generated by Django 6.0.7 on 2026-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videosetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosetting',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='版权信息'),
        ),
        migrations.AddField(
            model_name='videosetting',
            name='footer_description',
            field=models.TextField(blank=True, default='', verbose_name='页脚简介'),
        ),
        migrations.AddField(
            model_name='videosetting',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='平台名称'),
        ),
    ]
