# Generated by Django 6.0.7 on 2026-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videosetting_footer_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点击次数'),
        ),
    ]
