# Generated by Django 6.0.7 on 2026-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoalbum',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点击次数'),
        ),
    ]
