# Generated by Django 6.0.7 on 2026-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videoalbum_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosetting',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='首页横幅背景图'),
        ),
    ]
