# Generated by Django 6.0.7 on 2026-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=100, verbose_name='站点名称')),
                ('site_description', models.TextField(blank=True, verbose_name='站点描述')),
                ('default_language', models.CharField(default='zh-hans', max_length=10, verbose_name='默认语言')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='允许注册')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
