# Generated by Django 6.0.7 on 2026-08-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='版权信息'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_icp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ICP备案号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Footer 文字'),
        ),
    ]
