# Generated by Django 6.0.7 on 2026-08-03 07:42

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('system', '0002_siteconfig_footer_copyright_siteconfig_footer_icp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='站点Logo'),
        ),
    ]
