# Generated by Django 6.0.7 on 2026-07-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('camera', '摄像头'), ('display', '显示屏'), ('capture', '采集终端'), ('audio', '音频设备'), ('other', '其他')], default='other', max_length=20, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中')], default='offline', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='schools.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
