# Generated by Django 6.0.7 on 2026-08-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='', max_length=100, verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_sn',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='设备SN'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_token',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='设备令牌'),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='固件版本'),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_online_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='安装位置'),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='MAC地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='厂商'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('recording_host', '录播主机'), ('camera', '摄像头'), ('microphone', '麦克风'), ('speaker', '音箱'), ('terminal', '终端')], default='recording_host', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('offline', '离线'), ('online', '在线'), ('recording', '录制中'), ('streaming', '直播中'), ('uploading', '上传中'), ('error', '异常')], default='offline', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='直播标题')),
                ('stream_key', models.CharField(max_length=128, unique=True, verbose_name='推流密钥')),
                ('rtmp_push_url', models.CharField(max_length=255, verbose_name='RTMP推流地址')),
                ('hls_url', models.CharField(blank=True, default='', max_length=255, verbose_name='HLS观看地址')),
                ('status', models.CharField(choices=[('created', '已创建'), ('starting', '启动中'), ('live', '直播中'), ('stopped', '已停止'), ('error', '异常')], default='created', max_length=20, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='devices.device', verbose_name='设备')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='schools.school', verbose_name='学校')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='users.teacherprofile', verbose_name='教师')),
            ],
            options={
                'verbose_name': '直播会话',
                'verbose_name_plural': '直播会话',
            },
        ),
    ]
