# Generated by Django 6.0.7 on 2026-08-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_name_device_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='stream_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='一次性推流令牌'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='token_used',
            field=models.BooleanField(default=False, verbose_name='令牌已使用'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='devices.device', verbose_name='设备'),
        ),
    ]
