# Generated by Django 6.0.7 on 2026-08-03 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_building_alter_school_options_remove_school_country_and_more'),
        ('videos', '0008_videosetting_banner_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('local', '本地模型')], default='openai', max_length=20, verbose_name='提供商')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API密钥')),
                ('endpoint', models.CharField(blank=True, default='', max_length=500, verbose_name='API端点')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型配置',
                'verbose_name_plural': 'AI模型配置',
                'ordering': ['-priority', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('full', '完整分析'), ('video', '仅视频分析'), ('speech', '仅语音分析'), ('teaching', '教学评估')], default='full', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_tasks', to='schools.school', verbose_name='教室')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_tasks', to=settings.AUTH_USER_MODEL, verbose_name='教师')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': 'AI分析任务',
                'verbose_name_plural': 'AI分析任务',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', verbose_name='课堂总结')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键词')),
                ('knowledge_points', models.JSONField(blank=True, default=list, verbose_name='知识点')),
                ('teaching_score', models.FloatField(default=0, verbose_name='教学评分')),
                ('student_engagement_score', models.FloatField(default=0, verbose_name='学生参与度评分')),
                ('teacher_score', models.FloatField(default=0, verbose_name='教师综合评分')),
                ('suggestions', models.TextField(blank=True, default='', verbose_name='改进建议')),
                ('report_url', models.CharField(blank=True, default='', max_length=500, verbose_name='报告URL')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ai_analysis.classanalysistask', verbose_name='分析任务')),
            ],
            options={
                'verbose_name': 'AI分析结果',
                'verbose_name_plural': 'AI分析结果',
                'ordering': ['-created_time'],
            },
        ),
    ]
