# Generated by Django 6.0.7 on 2026-08-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
        ('schools', '0002_building_alter_school_options_remove_school_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='blackboard_content',
            field=models.JSONField(blank=True, default=list, verbose_name='黑板内容'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='classroom_environment',
            field=models.JSONField(blank=True, default=dict, verbose_name='教室环境'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='key_frames',
            field=models.JSONField(blank=True, default=list, verbose_name='关键帧列表'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='ppt_content',
            field=models.JSONField(blank=True, default=list, verbose_name='PPT内容'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='scene_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='场景分析'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='student_interaction',
            field=models.JSONField(blank=True, default=dict, verbose_name='学生互动'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='teacher_actions',
            field=models.JSONField(blank=True, default=list, verbose_name='教师动作'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='video_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='视频信息'),
        ),
        migrations.AddField(
            model_name='classanalysistask',
            name='current_step',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='当前步骤'),
        ),
        migrations.AlterField(
            model_name='classanalysistask',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_tasks', to='schools.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='classanalysistask',
            name='task_type',
            field=models.CharField(choices=[('full', '完整分析'), ('video', '仅视频分析'), ('speech', '仅语音分析'), ('teaching', '仅教学评估')], default='full', max_length=20, verbose_name='任务类型'),
        ),
    ]
