# Generated by Django 6.0.7 on 2026-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_aianalysisresult_blackboard_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='speaking_rate',
            field=models.JSONField(blank=True, default=dict, verbose_name='语速分析'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='speech_segments',
            field=models.JSONField(blank=True, default=list, verbose_name='语音片段'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='transcript',
            field=models.TextField(blank=True, default='', verbose_name='课堂文字稿'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('local', '本地模型'), ('openai_whisper', 'OpenAI Whisper'), ('gemini_speech', 'Gemini Speech'), ('azure_speech', 'Azure Speech'), ('local_whisper', '本地Whisper')], default='openai', max_length=20, verbose_name='提供商'),
        ),
    ]
