# Generated by Django 6.0.7 on 2026-08-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_aianalysisresult_speaking_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodelconfig',
            options={'ordering': ['priority', '-created_time'], 'verbose_name': 'AI模型配置', 'verbose_name_plural': 'AI模型配置'},
        ),
        migrations.AlterModelOptions(
            name='classanalysistask',
            options={'ordering': ['-created_time'], 'verbose_name': '课堂分析任务', 'verbose_name_plural': '课堂分析任务'},
        ),
        migrations.RemoveField(
            model_name='aimodelconfig',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='aimodelconfig',
            name='status',
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='evaluation_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='评价报告'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=list, verbose_name='改进建议'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='overall_score',
            field=models.FloatField(default=0, verbose_name='总分'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='api_base',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='API地址'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4096, verbose_name='最大Token数'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='温度'),
        ),
        migrations.AddField(
            model_name='classanalysistask',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='key_frames',
            field=models.JSONField(blank=True, default=list, verbose_name='关键帧'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='report_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='报告链接'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='student_engagement_score',
            field=models.FloatField(default=0, verbose_name='学生参与度'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='分析总结'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='teacher_score',
            field=models.FloatField(default=0, verbose_name='教师评分'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='API密钥'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('qianfan', '百度千帆'), ('dashscope', '阿里百炼'), ('openai_whisper', 'OpenAI Whisper'), ('gemini_speech', 'Gemini Speech'), ('azure_speech', 'Azure Speech'), ('local_whisper', '本地Whisper')], default='openai', max_length=30, verbose_name='AI服务商'),
        ),
        migrations.AlterField(
            model_name='classanalysistask',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='classanalysistask',
            name='task_type',
            field=models.CharField(choices=[('full', '完整分析'), ('video', '仅视频分析'), ('speech', '仅语音分析'), ('teaching', '仅教学评价')], default='full', max_length=20, verbose_name='任务类型'),
        ),
        migrations.CreateModel(
            name='TeachingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0, verbose_name='总分')),
                ('knowledge_score', models.FloatField(default=0, verbose_name='知识掌握度')),
                ('interaction_score', models.FloatField(default=0, verbose_name='互动参与度')),
                ('expression_score', models.FloatField(default=0, verbose_name='表达清晰度')),
                ('classroom_management_score', models.FloatField(default=0, verbose_name='课堂管理')),
                ('teaching_structure_score', models.FloatField(default=0, verbose_name='教学结构')),
                ('grade', models.CharField(blank=True, default='', max_length=20, verbose_name='等级')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='优势')),
                ('weaknesses', models.JSONField(blank=True, default=list, verbose_name='不足')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='建议')),
                ('evaluation_method', models.CharField(default='rule_based', max_length=20, verbose_name='评价方式')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='ai_analysis.classanalysistask', verbose_name='分析任务')),
            ],
            options={
                'verbose_name': '教学评价',
                'verbose_name_plural': '教学评价',
                'ordering': ['-created_time'],
            },
        ),
    ]
