# Generated by Django 6.0.7 on 2026-08-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_alter_aimodelconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='报告标题')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='课堂总结')),
                ('teacher_report', models.JSONField(blank=True, default=dict, verbose_name='教师报告')),
                ('school_report', models.JSONField(blank=True, default=dict, verbose_name='学校报告')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='PDF文件')),
                ('html_content', models.TextField(blank=True, default='', verbose_name='HTML内容')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ai_analysis.classanalysistask', verbose_name='分析任务')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
                'ordering': ['-created_time'],
            },
        ),
    ]
