# Generated by Django 5.2 on 2026-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0005_aireport'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='model_type',
            field=models.CharField(choices=[('chat', '文本对话'), ('vision', '视觉分析'), ('speech_to_text', '语音识别'), ('embedding', '向量嵌入'), ('multimodal', '多模态')], default='chat', max_length=30, verbose_name='模型类型'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='timeout',
            field=models.PositiveIntegerField(default=60, verbose_name='超时时间(秒)'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='API密钥'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('qwen', '阿里通义千问'), ('deepseek', 'DeepSeek'), ('glm', '智谱 GLM'), ('ollama', 'Ollama 本地模型')], default='openai', max_length=30, verbose_name='AI服务商'),
        ),
    ]
