# Generated by Django 5.2 on 2026-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0006_aimodelconfig_description_aimodelconfig_model_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='api_endpoint',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='私有部署端点'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, verbose_name='能力配置'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='deployment_type',
            field=models.CharField(choices=[('cloud', '云服务'), ('private', '私有部署'), ('local', '本地模型'), ('hybrid', '混合部署')], default='cloud', max_length=20, verbose_name='部署类型'),
        ),
    ]
