# Generated by Django 5.2 on 2026-08-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0007_aimodelconfig_api_endpoint_and_more'),
        ('schools', '0003_alter_building_id_alter_school_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='health_status',
            field=models.CharField(choices=[('active', '正常'), ('degraded', '降级'), ('offline', '离线')], default='active', max_length=20, verbose_name='健康状态'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='last_error_message',
            field=models.TextField(blank=True, default='', verbose_name='最后错误信息'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='last_health_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间'),
        ),
        migrations.AddField(
            model_name='classanalysistask',
            name='model_config',
            field=models.ForeignKey(blank=True, help_text='指定使用的模型配置，为空则自动选择', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_tasks', to='ai_analysis.aimodelconfig', verbose_name='模型配置'),
        ),
        migrations.CreateModel(
            name='OrganizationAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_token_limit', models.PositiveIntegerField(default=0, help_text='每月Token限制，0表示无限制', verbose_name='每月Token限制')),
                ('monthly_cost_limit', models.DecimalField(decimal_places=2, default=0, help_text='每月成本限制，0表示无限制', max_digits=10, verbose_name='每月成本限制')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allowed_models', models.ManyToManyField(blank=True, related_name='allowed_for_organizations', to='ai_analysis.aimodelconfig', verbose_name='允许使用的模型')),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_organizations', to='ai_analysis.aimodelconfig', verbose_name='默认模型')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='schools.school', verbose_name='组织/学校')),
            ],
            options={
                'verbose_name': '组织AI配置',
                'verbose_name_plural': '组织AI配置',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='任务ID')),
                ('provider', models.CharField(blank=True, default='', max_length=30, verbose_name='AI服务商')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='模型名称')),
                ('task_type', models.CharField(choices=[('video_analysis', '视频分析'), ('speech_analysis', '语音分析'), ('teaching_evaluation', '教学评价'), ('report_generation', '报告生成'), ('chat', '对话'), ('embedding', '向量嵌入')], default='chat', max_length=30, verbose_name='任务类型')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='输入Token数')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='输出Token数')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='总Token数')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='预估成本')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='货币单位')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('response_time', models.FloatField(default=0, verbose_name='响应时间(秒)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('degraded', '降级')], default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai_analysis.aimodelconfig', verbose_name='模型配置')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='schools.school', verbose_name='组织/学校')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI使用日志',
                'verbose_name_plural': 'AI使用日志',
                'ordering': ['-request_time'],
                'indexes': [models.Index(fields=['provider', 'model_name'], name='ai_analysis_provide_09e56e_idx'), models.Index(fields=['task_type'], name='ai_analysis_task_ty_49d15d_idx'), models.Index(fields=['status'], name='ai_analysis_status_b7a8f0_idx'), models.Index(fields=['request_time'], name='ai_analysis_request_86d33d_idx')],
            },
        ),
    ]
