# Generated by Django 6.0.7 on 2026-07-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='直播间名称')),
                ('status', models.CharField(choices=[('scheduled', '待开播'), ('live', '直播中'), ('ended', '已结束')], default='scheduled', max_length=20, verbose_name='状态')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='预约时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_rooms', to='schools.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '直播间',
                'verbose_name_plural': '直播间',
            },
        ),
    ]
