"""
Django settings for video_platform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7=cw)z$46h9__#n317+3kp5%94@6gm5$^#uf1xo^zn015c8_m^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
USE_X_FORWARDED_HOST = True

ALLOWED_HOSTS = ['*']


# Application definition

SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_TITLE = _('首页')
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_SETTINGS = {
    'CSS_URL': '/static/admin/css/custom.css',
}

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'videos.apps.VideosConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'users.apps.UsersConfig',
    'schools.apps.SchoolsConfig',
    'devices.apps.DevicesConfig',
    'live.apps.LiveConfig',
    'reviews.apps.ReviewsConfig',
    'system.apps.SystemConfig',
]

SIMPLEUI_ICON = {
    '用户': 'fas fa-user', 'User': 'fas fa-user',
    '学校': 'fas fa-school', 'School': 'fas fa-school',
    '教师资料': 'fas fa-chalkboard-teacher', 'Teacher Profile': 'fas fa-chalkboard-teacher',
    '教学楼': 'fas fa-building', 'Building': 'fas fa-building',
    '教室': 'fas fa-door-open', 'Room': 'fas fa-door-open',
    '视频分类': 'fas fa-tags', 'Video Category': 'fas fa-tags',
    '视频': 'fas fa-video', 'Video': 'fas fa-video',
    '视频专辑': 'fas fa-folder-open', 'Video Album': 'fas fa-folder-open',
    '审核记录': 'fas fa-clipboard-check', 'Review Log': 'fas fa-clipboard-check',
    '视频设置': 'fas fa-sliders-h', 'Video Settings': 'fas fa-sliders-h',
    '设备': 'fas fa-server', 'Device': 'fas fa-server',
    '直播会话': 'fas fa-broadcast-tower', 'Live Session': 'fas fa-broadcast-tower',
    '直播间': 'fas fa-radio', 'Live Room': 'fas fa-radio',
    '评价': 'fas fa-star', 'Review': 'fas fa-star',
    '系统设置': 'fas fa-cog', 'System Settings': 'fas fa-cog',
    '认证令牌': 'fas fa-key', 'Authentication Tokens': 'fas fa-key',
    '令牌': 'fas fa-key', 'Tokens': 'fas fa-key',
    'Users': 'fas fa-users',
    'Schools': 'fas fa-school',
    'Videos': 'fas fa-video',
    'Devices': 'fas fa-server',
    'Live': 'fas fa-broadcast-tower',
    'Reviews': 'fas fa-star',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'system.middleware.SiteConfigMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'video_platform.urls'

AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'video_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if os.environ.get('DB_ENGINE') == 'postgres':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'video_platform'),
        'USER': os.environ.get('DB_USER', 'video'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'video123456'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('zh-hant', '繁體中文'),
    ('en', 'English'),
    ('ko', '한국어'),
    ('vi', 'Tiếng Việt'),
    ('ru', 'Русский'),
    ('ms', 'Bahasa Melayu'),
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

LOCALE_PATHS = [BASE_DIR / 'video_platform' / 'locale']

USE_TZ = True


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
MEDIA_ROOT = BASE_DIR / 'media'

RTMP_SERVER_URL = os.environ.get('RTMP_SERVER_URL', 'rtmp://127.0.0.1:1935')
HLS_SERVER_URL = os.environ.get('HLS_SERVER_URL', 'http://127.0.0.1:8080')
# 鏂板 CSRF 淇′换鍓嶇婧愶紝瑙ｅ喅403 Origin鏍￠獙澶辫触
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]
