# Generated by Django 6.0.7 on 2026-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='学校名称')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='国家')),
                ('language', models.CharField(blank=True, default='zh-hans', max_length=50, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
    ]
