# Generated by Django 6.0.7 on 2026-08-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='教学楼名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '教学楼',
                'verbose_name_plural': '教学楼',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_at'], 'verbose_name': '教室', 'verbose_name_plural': '教室'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='country',
        ),
        migrations.RemoveField(
            model_name='school',
            name='language',
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200, verbose_name='教室名称'),
        ),
        migrations.AddField(
            model_name='school',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='schools.building', verbose_name='所属教学楼'),
        ),
    ]
